name = "perex-noon-manager"
main = "src/src/src/src/index.js"
compatibility_date = "2026-09-22"

[observability]
enabled = true

[vars]
NOON_BASE_URL = "https://noon-api-gateway.noon.partners"
NOON_REPORT_CODE = "EXP4E2HD6HA4"
TARGET_PARTNER_SKU = "159-BRD340"
# Trigger Cloudflare deployment
